### PR TITLE
Added basic settings option

### LINKED ISSUE #32: Settings options
The user shall be able to change temperature units or set favorite location etc.

Conversion from Celsius to Fahrenheit is also included, this is done by calculating the temperature in Fahrenheit instead of making another call

### PR DESCRIPTION
**Pull request by ketelaar**
Resolves #32 

For now I have implemented the ability to change temperatures, but there are some things that could be addressed in this PR:

- The temperature unit preference is only saved during the execution of the app, the app does not remember the preference on startup. Fixing this would (probably) involve sending the preference to the backend which handles local storage
- I also did not implement the "favorite" location feature, do we want to do this still for this PR? At the moment there is no UI for it so that's why I didn't choose to implement it.

### CODE REVIEW

**Comment by ketelaar** [comment]
I fixed the settings button not having the correct color in light mode (commit 2b0699c) @mdvmeijer

**Comment by kunkuma** [comment]
> Resolves #32
> 
> For now I have implemented the ability to change temperatures, but there are some things that could be addressed in this PR:
> 
>     * The temperature unit preference is only saved during the execution of the app, the app does not remember the preference on startup. Fixing this would (probably) involve sending the preference to the backend which handles local storage
> 
>     * I also did not implement the "favorite" location feature, do we want to do this still for this PR? At the moment there is no UI for it so that's why I didn't choose to implement it.

On the first point, shall we create a new task for that? I think that would be better. The favorite location feature is something that we can also add later. I don't think we need to have that in settings eventually. It can be placed somewhere else. If agree with these, I'll approve and merge the PR. It looks good.

**Comment by ketelaar** [comment]
Sure that sounds good @kunkuma, I've made issue #49 and #50 for them and added them to the Version 2 milestone.

**Review by kunkuma — APPROVED** [review]
Thank you @ketelaar. The changes look good.

**Pull request merged**
